### ISSUE TITLE
Deserialization Error...

### ISSUE THREAD

**Issue by Tronix82** [NickstaDB/SerializationDumper#10]
java -jar SerializationDumper-v1.11.jar file.bin

Unknown RMI packet type - 0xef
STREAM_MAGIC - 0xfe fb
Invalid STREAM_MAGIC, should be 0xac ed

**Comment by NickstaDB** [comment]
Hi @Tronix82, looks like your data isn't in Java's serialization format. Data in this format begins with the hex bytes `AC ED`, although SerializationDumper also supports dumping data from Java Remote Method Invocation packets which start with a byte in the range hex `50` to hex `54`. Your data begins with hex `EF FE`.

Where did you get the data in _file.bin_ from? Are you certain it was written using `ObjectOutputStream.write*`? Are you able to read it using `ObjectInputStream.read*`?

**Comment by Tronix82** [comment]
Hello, 
My file is 100% Java serialized file. The magic stream bytes are inside file. The serialized file was made using apache serialization utility. Can I send you the to check? 
Thank for your help. 
Best Regards, 
Sent from Yahoo Mail on Android

**Comment by NickstaDB** [comment]
If you can share a sample of the file that would certainly help. Also, what version of Java and Apache Commons Lang/SerializationUtils was used to create the file?

I've created my own test file using SerializationUtils from Apache Commons Lang 2.6 and the data that was output was in Java's serialization format, but your output from SerializationDumper indicates that the file you were trying to dump began with the hex bytes `EF FE FB`, rather than the `AC ED` that SerializationDumper expects.

**Comment by Tronix82** [comment]
Hello,
Please, find the attached file. The Apache version used is 2.5. This file contains a public RSA value.
Best Regards,
Tronix

**Comment by NickstaDB** [comment]
Hi @Tronix82, there's no file attached to your reply. You may need to attach the file via github.com rather than in an email response.

**Comment by Tronix82** [comment]
[RSA-KEY.zip](https://github.com/NickstaDB/SerializationDumper/files/4449757/RSA-KEY.zip)

**Comment by NickstaDB** [comment]
Ah I missed the issue in your first comment, the problem is in how you're running the tool.

```
Usage:
	SerializationDumper <hex-ascii-data>
	SerializationDumper -f <file-containing-hex-ascii>
	SerializationDumper -r <file-containing-raw-data>

Rebuild a dumped stream:
	SerializationDumper -b <input-file> <output-file>
```

When you run `SerializationDumper.jar` with a single parameter it is expected to be the raw data encoded as hex, not a filename. Your sample file contains raw serialized data so you'll want to run `SerializationDumper.jar -r file.bin`.

**Comment by Tronix82** [comment]
Yes.. Thank you its working now..
