### ISSUE TITLE
error: Unknown... Invalid

### ISSUE THREAD

**Issue by hktalent** [NickstaDB/SerializationDumper#6]
```
Unknown RMI packet type - 0xf3
STREAM_MAGIC - 0xfd f7
Invalid STREAM_MAGIC, should be 0xac ed
```

**Comment by NickstaDB** [comment]
Your data is not in the Java serialization stream format. The first two bytes should be 0xAC 0xED (see https://docs.oracle.com/javase/7/docs/platform/serialization/spec/protocol.html), otherwise the program checks if it's a Java Remote Method Invocation (RMI) message and if so prints out the RMI message type before attempting to parse the message body as a Java serialized stream. The byte 0xf3 is not a valid RMI message type (see https://docs.oracle.com/javase/8/docs/platform/rmi/spec/rmi-protocol3.html).
